server:
  port: 8001


spring:
  application:
    name: mysql-ecable-provider8001
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://152.136.124.219:3306/e_cable?useUnicode=true&characterEncoding=utf-8&useSSL=false
    url1: jdbc:mysql://81.70.6.45:3306/e_cable?useUnicode=true&characterEncoding=utf-8&useSSL=false
    url2: jdbc:mysql://81.70.6.45:3306/e_cable?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: janson
    password: Snynitfqm$janson10254415


mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml


management:
  endpoints:
    web:
      exposure:
        include: '*'



