server:
  port: 9001

spring:
  application:
    name: ecable-backstage9001
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://152.136.124.219:3306/e_cable?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: janson
    password: Snynitfqm$janson10254415

#消费者将要去访问的微服务名称(注册成功进nacos的微服务提供者)
service-url:
  nacos-user-service: http://mysql-ecable-provider8001
  nacos-mine-service: http://ecable-backstage9001

