server:
  port: 9001

spring:
  application:
    name: ecable-backstage9001
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

mybatis:
  type-aliases-package: com.lanhangbao.ecable.entities    # 所有Entity别名类所在包

#消费者将要去访问的微服务名称(注册成功进nacos的微服务提供者)
service-url:
  nacos-user-service: http://mysql-ecable-provider8001

